<<<<<<< HEAD
; Variable naming conventions:
; G_xxx  => Global variables
; HH_xxx => Household breed variables
; MP_xxx => Municipality breed variables
; RC_xxx => Recycling company variables
; CT_xxx => Contract variables
; _xxx   => Local variable carrying parameters in function
; xxx    => Local variable in function

; Function naming conventions:
; with the exception of the "go" and "setup" function (for the sake of conformity),
; function names have capitalized words which are seperated by a dash (-)

; Comment key conventions:
; REF-N  => Reference needed
; REF-## => Reference provided. ## relates to the description provided in the Info --> References
; ASS-N  => Formal assumption needed
; ASS-## => Formal assumption provided. ## relates to the description provided in Info --> Assumptions

; Definition of key terms:
; Waste - Total amount of combined waste generated by households inclusive of all types (ie. plastic, paper, organic, etc.)
; Plastic waste - Total amount of plastic that is removed from waste by the household (inclusive of both recyclable and non-recyclable plastics)
; Recyclable waste - Total amount of recyclable plastic waste within the plastic waste

;=================================================================================
;    Part 1: Global variables
;=================================================================================

globals [
  ;----------------------- Household related ------------------
  G_household_total_plastic_pct    ;; Percent of total household waste that is plastic
  G_household_total_recyclable_pct ;; Percentage of total household plastic waste that is recyclable
  G_initial_perception_avg         ;; An indicator in range 0.00 - 1.00 for the average initial perception
  G_initial_knowledge_avg          ;; An indicator in range 0.00 - 1.00 for the average initial knowledge
  G_occupancy_qty_list             ;; A list in which each number represents the occupancy quantity matching that given index
                                   ;; (0 = family [4 people], 1 = couple [2 people], 2 = single [1 person], 3 = senior [2 people])
  G_infrastructure_impact          ;; % difference of plastic waste collected using centralized vs decentralized systems

  ;------------------- Recycling company related --------------
  G_tech_capacity_avg              ;; Average processing capacity at current time
  G_tech_sep_eff_avg               ;; Average separation efficiency at current time
  G_recycled_plastic_price         ;; Market price for recycled plastic

  ;---------------------- Municipality related ----------------
  G_target                         ;; Annual recycling target for municipalities set by national government
  G_pct_budget_spending            ;; The percentage of the budget that should be spent on education (knowledge & perception increases)
  G_pct_education_split            ;; The distribution of education budget on knowledge vs. perception (0.5 is equally distributed)
  G_budget_per_person              ;; The recycling budget per person
  ]

;=================================================================================
;    Part 2: Breed declarations and specifications
;=================================================================================

breed [HHs HH]                   ;; Households
breed [MPs MP]                   ;; Municipalities
breed [RCs RC]                   ;; Recycling Companies
breed [Contracts Contract]       ;; Contracts

HHs-own [
  HH_owner                       ;; The municipality that the household belongs to
  HH_occupancy                   ;; Type of occupancy (0 = family [4 people], 1 = couple [2 people], 2 = single [1 person], 3 = senior [2 people])
  HH_perception                  ;; Percentage representing the perception of importance of recycling
  HH_knowledge                   ;; Percentage representing the knowledge of proper recycling
  HH_total_waste
  HH_plastic_waste
  HH_recyclable_waste
]

MPs-own [
  MP_list_of_HHs                 ;; List of households in the municipality
  MP_budget                      ;; Monthly recycling budget of the municipality
  MP_infrastructure              ;; Type of infrastructure (0 = centralized, 1 = decentralized)                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  MP_months_overbudget           ;; How many months the municipality has gone over their recycling budget        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  MP_my_contracts                 ;; Link to the current recycling contract held by the municipality
  MP_total_waste
  MP_plastic_waste
  MP_recyclable_waste
  MP_pct_recycled
]

RCs-own [
  RC_list_of_techs               ;; List of technologies operated by the recycling company
  RC_list_of_contracts           ;; List of contracts held by the recycling company                              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  RC_account_balance             ;; Account balance of the recycling company
]

Contracts-own [
  CT_MP_own                      ;; Municipality that owns the contract
  CT_RC_own                      ;; Recycling company that owns the contract
  CT_capacity                    ;; The maximum amount that these contracts can process
  CT_sep_eff                     ;; Separation efficiency of the process
  CT_monthly_fee                 ;; Monthly fee paid to RC
  CT_fine                        ;; Fine to be levied should the MP not meet the min_waste
  CT_fine_levied                 ;; This variable carries either 0 or CT_fine depending on wether recycling targets were met
  CT_overallrank                 ;; Used to rank contracts against each other
  CT_active                      ;; Whether or not the contract has been accepted by the MP and activated
]

;=================================================================================
;    Part 3.1: Function definitions - Program flow
;=================================================================================

; The setup function has to be run before the go button is pushed,
; and executes only ONCE per simulation
to setup

  ; Create an empty space for the model to run in
  clear-all
  reset-ticks

  ; Give values to the global variables [some based on slider input]
  ;----------------------- Household related ------------------
  set G_initial_perception_avg 0.5                                        ;; slider 0-100%
  set G_initial_knowledge_avg 1                                           ;; slider 0-100%
  set G_household_total_plastic_pct 0.1                                   ;; slider 0-100%
  set G_household_total_recyclable_pct 0.5                                ;; slider 0-100%
  set G_occupancy_qty_list (list 4 2 1 2)                                 ;;
  ;---------------------- Municipality related ----------------
  set G_pct_budget_spending 1                                             ;; slider 0-100%
  set G_pct_education_split 0.5                                           ;; slider 0-100%
  set G_infrastructure_impact 0.5                                         ;; slider 0-100%
  ;------------------- Recycling company related --------------
  set G_tech_capacity_avg 5000                                              ;; slider
  set G_tech_sep_eff_avg 0.85                                              ;; slider 0-100%

  ; Create the households and municipalities
  create-MPs 3
  create-HHs 30 [
    set HH_owner one-of MPs                                               ;; households get assigned to a municipality randomly
    set HH_occupancy random 4                                             ;; sets occupancy type randomly
    set HH_perception G_initial_perception_avg                            ;;* (1 + (random 50 - 25) / 100)
    set HH_knowledge G_initial_knowledge_avg                              ;;* (1 + (random 50 - 25) / 100)
  ]
  ask MPs [
    set MP_list_of_HHs HHs with [HH_owner = myself]                       ;; municipalities gather their households
    set MP_budget 10 * count MP_list_of_HHs                               ;; budget based on number of households
    set MP_infrastructure random 2                                        ;; infrastruction (centralized/de-centralized) assigned randomly
    set MP_months_overbudget 0
  ]

  ; Create the recycling companies
  create-RCs 2 [
    let capacity G_tech_capacity_avg                                      ;; * (1 + (random 50 - 25) / 100)
    let sep_eff G_tech_sep_eff_avg                                        ;; * (1 + (random 10 - 5) / 100)
    let tech (list capacity sep_eff 0 0)
    set RC_list_of_techs (list tech)
  ]

  create-Contracts 2

end

; This is the main loop of the simulation, and executes on every tick
to go

  ; On every tick (representing 1 month) waste gets collected

  ask MPs [ MP-Collect-Waste ]

  ; On tick 0, and every 36 ticks (=3 years) generate new contracts for each municipality
  if ticks mod 36 = 0 [
    output-print (word "Bidding for year:" round (ticks / 12))
    ask MPs [MP-Select-Bid]
  ]

  ; Perform the waste transfer, use remaining money on perception and knowledge change
  ask MPs [
    MP-Transfer
    ;MP-Perception-Change MP_budget * G_pct_budget_spending * G_pct_education_split
    ;MP-Knowledge-Change MP_budget * G_pct_budget_spending * (1 - G_pct_education_split)
  ]

  ; Proceed to the following tick
  tick

end

;=================================================================================
;    Part 3.2: Function definitions - Municipalities
;=================================================================================

; Calculate total waste generated by each type of household as well as the breakdown of plastic and recyclable plastic
to MP-Collect-Waste

  let total_waste 0
  let plastic_waste 0

  set MP_total_waste 0
  set MP_plastic_waste 0
  set MP_recyclable_waste 0

  ask MP_list_of_HHs [

    set total_waste HH-gather-waste (HH_occupancy)
    set plastic_waste total_waste * G_household_total_plastic_pct

    ; Maybe this stuff down here has to be broken down into parts if we have time left. A bit too much linecramming :(
    ; Hard to understand for an outsider
    ask myself [
      set MP_total_waste MP_total_waste + total_waste
      set MP_plastic_waste MP_plastic_waste + plastic_waste * [HH_perception] of myself * (G_household_total_recyclable_pct + (1 - G_household_total_recyclable_pct) * (1 - [HH_knowledge] of myself))
      set MP_recyclable_waste MP_recyclable_waste + plastic_waste * [HH_perception] of myself * (G_household_total_recyclable_pct)
    ]
  ]
  if MP_infrastructure = 0 [
    set MP_plastic_waste MP_plastic_waste * G_infrastructure_impact
    set MP_recyclable_waste MP_recyclable_waste * G_infrastructure_impact
    ]
  set MP_total_waste round MP_total_waste
  set MP_plastic_waste round MP_plastic_waste
  set MP_recyclable_waste round MP_recyclable_waste
end

; This function clears the current contracts, asks companies to generate new ones and picks the best options
to MP-Select-Bid

  ; Clear the previous contract
  ask Contracts with [CT_MP_own = self] [die]

  ; Generate a list of bids from recycling companies
  let bids []
  ask RCs [
    let bid RC-Prepare-Bid
    if item 2 bid != 0 [set bids lput (bid) bids]
  ]
  ; Create a contract agent for each bid to be assessed
  foreach bids [ [?1] ->
    hatch-Contracts 1 [
      set CT_MP_own myself
      set CT_RC_own item 1 ?1
      set CT_capacity item 2 ?1
      set CT_sep_eff item 3 ?1
      set CT_monthly_fee item 4 ?1
      set CT_fine item 5 ?1
      set CT_active 0
    ]
  ]
  let winners MP-Pick-Winners
  foreach winners [ [?1] ->
    ask ?1 [set CT_MP_own myself]

  ]

  ask contracts with [CT_active = 0] [die]
  set MP_my_contracts Contracts with [CT_MP_own = myself]     ;; municipalities gather their contracts
end

; This function ranks the available contracts based on fee, fine and requirements and picks the most ideal one
to-report MP-Pick-Winners

  let contracts_total_capacity 0
  let contract_list Contracts with [CT_MP_own = myself]


  let contracts_picked []

  ;;let lowest_fee sort-on [CT_monthly_fee] contract_list
  let lowest_fine sort-on [CT_fine] contract_list
  let lowest_reqs sort-on [CT_capacity] contract_list

  ask contract_list [
    set CT_overallrank mean (list position self lowest_fine position self lowest_reqs)
  ]

  ; Keep adding contracts until the requirements are met
  let contract_ranking sort-on [CT_overallrank] contract_list
  foreach contract_ranking [ [?1]->
    if MP_plastic_waste - contracts_total_capacity > 0 [
      set contracts_picked lput ?1 contracts_picked
      ask ?1 [
        if CT_capacity + contracts_total_capacity >  [MP_plastic_waste] of myself [
          set CT_capacity  [MP_plastic_waste] of myself - contracts_total_capacity
        ]
        set contracts_total_capacity contracts_total_capacity + CT_capacity
        set CT_active 1
      ]
    ]
  ]

  report contracts_picked
end

to MP-Transfer
  ask MP_my_contracts [
    let qty_total 0
    let qty_plastic_waste 0
    let qty_recyclable_waste 0
    ask CT_MP_own [
      set qty_total MP_total_waste
      set qty_plastic_waste MP_plastic_waste
      set qty_recyclable_waste MP_recyclable_waste
    ]
    let pct_reduction CT_capacity / qty_plastic_waste
    set qty_plastic_waste qty_plastic_waste - CT_capacity
    set qty_total qty_total - CT_capacity
    ifelse qty_plastic_waste < CT_capacity [set CT_fine_levied CT_fine * (CT_capacity - qty_plastic_waste)][set CT_fine_levied 0]
    let monthly_fee CT_monthly_fee * qty_plastic_waste
    let fine CT_fine_levied
    ask CT_RC_own [
      set RC_account_balance RC_account_balance + monthly_fee + fine - Operating-Cost RC-Capacity RC-Separation-Efficiency  * qty_plastic_waste * 0.85 ;; [!!!] + qty_recyclable_waste * pct_reduction * RC-Separation-Efficiency * G_recycled_plastic_price
    ]
    ask CT_MP_own [
      set MP_budget MP_budget - (monthly_fee + fine)
      set MP_total_waste qty_total
      set MP_plastic_waste qty_plastic_waste
      set MP_recyclable_waste MP_recyclable_waste * (1 - pct_reduction)
    ]
  ]
end

to MP-Perception-Change [my_budget]
  ;;insert function
end

to MP-Knowledge-Change [my_budget]
  ;;insert function
end

to-report MP-Population
    let families count MP_list_of_HHs with [HH_occupancy = 0]
    let couples count MP_list_of_HHs with [HH_occupancy = 1]
    let singles count MP_list_of_HHs with [HH_occupancy = 2]
    let senors count MP_list_of_HHs with [HH_occupancy = 3]
    let total families * 4 + couples * 2 + singles * 1 + senors * 2
    report total
end

;=================================================================================
;    Part 3.2: Function definitions - Households
;=================================================================================

;;Calculate total waste generated by each type of household
to-report HH-Gather-Waste [my_occupancy]
  let my_waste (40 - 0.04 * ticks - exp(-0.01 * ticks) * sin(0.3 * ticks * 180 / pi)) / 1000
  set my_waste my_waste * item my_occupancy G_occupancy_qty_list
  if my_occupancy = 3 [set my_waste my_waste * 0.4]
  report my_waste
end
;;---------------------------------------------------------------------------

;=================================================================================
;    Part 3.2: Function definitions - Recycling companies
;=================================================================================

to-report RC-Prepare-Bid ;; turtle procedure
  let total_capacity 0
  let total_separated 0
  foreach RC_list_of_techs [ [?1] ->
    set total_capacity total_capacity + item 0 ?1
    set total_separated total_separated + item 0 ?1 * item 1 ?1
    ]
  let total_sep_eff total_separated / total_capacity
  ask Contracts with [CT_RC_own = myself] [
    set total_capacity total_capacity - CT_capacity
  ]

  let bid (list 0 self total_capacity total_sep_eff 0 ((Operating-Cost total_capacity total_sep_eff) + G_recycled_plastic_price)) ;;Calculate monthly fee and fine
  report bid
end

to-report RC-Capacity
  let total 0
  foreach RC_list_of_techs [ [?1] ->
    set total total + item 0 ?1
  ]
  report total
end

to-report RC-Separation-Efficiency
  let total 0
  let separated_total 0
  foreach RC_list_of_techs [ [?1] ->
    set total total + item 0 ?1
    set separated_total separated_total + item 0 ?1 * item 1 ?1
  ]
  report separated_total / total
end

to-report Operating-Cost [_capacity _sep_eff]
  report round (-135 / 40000 * _capacity / (1 + (_sep_eff - G_tech_sep_eff_avg)) + 215 * (1 + (_sep_eff - G_tech_sep_eff_avg)))
end
;;---------------------------------------------------------------------------

;=================================================================================
;    Part 4: Validation Functions
;=================================================================================
; These functions can be run to validate the operation of the functions. The
; inputs and outputs are provided so that the results can be compared with
; hand calculations.

; Validation of bidding process functions:
; MP-Select-Bid, RC-Prepare-Bid, MP-Pick-Winners
to setup-bid-validation
  ; Create an empty space for the model to run in
  clear-all
  reset-ticks

  ; Give values to the global variables
  ;------------------- Recycling company related --------------
  set G_tech_capacity_avg 5000                                             ;; slider
  set G_tech_sep_eff_avg 0.85                                              ;; slider 0-100%

  ; Create the households and municipalities
  create-MPs 2 [
    set MP_total_waste 20000
    set MP_plastic_waste 4000
    set MP_recyclable_waste 3000
  ]

  ; Create the recycling companies
  create-RCs 10 [
    let capacity round G_tech_capacity_avg * (1 + (random 50 - 25) / 100)
    let sep_eff min list (G_tech_sep_eff_avg * (1 + (random 10 - 5) / 100)) 1
    let tech (list capacity sep_eff 0 0)
    set RC_list_of_techs (list tech)
  ]

  ask MPs [

    let bids []
    ask RCs [
      let bid RC-Prepare-Bid
      set bids lput (bid) bids
    ]

    output-print (word "Municipality: " self)
    output-print (word "Waste generation rate (/month): " MP_plastic_waste)
    output-print "-------------------------"
    output-print "Bids presented by Recycling Companies"
    output-print (word "RC-own/capacity/sep eff/fee/fine")
    foreach bids [ [?1] ->
      output-print (word item 1 ?1 "    " round item 2 ?1 "    " (round (item 3 ?1 * 100) / 100) "    " item 4 ?1 "    " item 5 ?1)
    ]
    output-print "-------------------------"
    MP-Select-Bid
    output-print "Winning Bids:"
    output-print "RC-own/Capacity/Overall Rank"
    ask MP_my_contracts [output-print (word CT_RC_own "  " CT_capacity "  " CT_overallrank)]
    output-print ""
  ]

end

; Validation of waste generation and collection functions:
; HH-Gather-Waste and MP-Collect-Waste
to setup-waste-validation

  ; Create an empty space for the model to run in
  clear-all
  reset-ticks

  ; Give values to the global variables
  ;----------------------- Household related ------------------
  set G_initial_perception_avg 1                                          ;; slider 0-100%
  set G_initial_knowledge_avg 0.5                                          ;; slider 0-100%
  set G_household_total_plastic_pct 1                                  ;; slider 0-100%
  set G_household_total_recyclable_pct 0.5                                ;; slider 0-100%
  set G_occupancy_qty_list (list 4 2 1 2)                                 ;;
  ;---------------------- Municipality related ----------------
  set G_pct_budget_spending 1                                             ;; slider 0-100%
  set G_pct_education_split 0.5                                           ;; slider 0-100%
  set G_infrastructure_impact 1                                         ;; slider 0-100%

  ; Create the households and municipalities
  create-MPs 1
  create-HHs 5 [
    set HH_owner one-of MPs                                               ;; households get assigned to a municipality randomly
    set HH_occupancy random 4                                             ;; sets occupancy type randomly
    set HH_perception G_initial_perception_avg                            ;;* (1 + (random 50 - 25) / 100)
    set HH_knowledge G_initial_knowledge_avg                              ;;* (1 + (random 50 - 25) / 100)
  ]
  ask MPs [
    set MP_list_of_HHs HHs with [HH_owner = myself]                       ;; municipalities gather their households
    set MP_budget 10 * count MP_list_of_HHs                               ;; budget based on number of households
    set MP_infrastructure random 2                                        ;; infrastruction (centralized/de-centralized) assigned randomly
    set MP_months_overbudget 0
  ]
  ask MPs [
    output-print (word "Households (HH) created: " count MP_list_of_HHs)
    let families count MP_list_of_HHs with [HH_occupancy = 0]
    let couples count MP_list_of_HHs with [HH_occupancy = 1]
    let singles count MP_list_of_HHs with [HH_occupancy = 2]
    let senors count MP_list_of_HHs with [HH_occupancy = 3]

    output-print (word "# of Family HHs: " families)
    output-print (word "# of Couple HHs: " couples)
    output-print (word "# of Single HHs: " singles)
    output-print (word "# of Senor HHs:  " senors)
    output-print (word "Total population: " MP-Population)
    output-print "-------------------------"
    output-print "(1) Executing function 'HH-Gather-Waste'"
    output-print (word "Waste from Family HHs: " HH-gather-waste 0)
    output-print (word "Waste from Couple HHs: " HH-gather-waste 1)
    output-print (word "Waste from Single HHs: " HH-gather-waste 2)
    output-print (word "Waste from Senor HHs: " HH-gather-waste 3)
    output-print "-------------------------"
    output-print "(2) Executing function 'MP-Collect-Waste'"

    output-print (word "% of Total waste that is Plastic): " (G_household_total_plastic_pct * 100) "%")
    output-print (word "% of Plastic waste that is Recyclable: " (G_household_total_recyclable_pct * 100) "%")
    output-print (word "HH Perception of Importance: " (G_initial_perception_avg * 100) "%")
    output-print (word "HH Knowledge: " (G_initial_knowledge_avg * 100) "%")
    ifelse MP_infrastructure = 0 [output-print (word "Infrastructure: Centralized")][output-print (word "Infrastructure: De-centralized")]
    output-print (word "% diff of central vs de-central " (G_infrastructure_impact * 100) "%")
    output-print ""
    MP-Collect-Waste
    output-print (word "Municipality total waste: " MP_total_waste)
    output-print (word "Municipality plastic waste: " MP_plastic_waste)
    output-print (word "Municipality recyclable plastic waste: " MP_recyclable_waste)
  ]
end

; Validation of waste transfer and accounting functions:
; MP-Transfer, MP-Educate
to setup-transfer-validation
  ; Create an empty space for the model to run in
  clear-all
  reset-ticks

  ; Give values to the global variables
  ;----------------------- Household related ------------------
  set G_initial_perception_avg 1                                          ;; slider 0-100%
  set G_initial_knowledge_avg 1                                          ;; slider 0-100%
  set G_household_total_plastic_pct 1                                  ;; slider 0-100%
  set G_household_total_recyclable_pct 1                               ;; slider 0-100%
  set G_occupancy_qty_list (list 4 2 1 2)                                 ;;
  set G_budget_per_person 100
  ;---------------------- Municipality related ----------------
  set G_pct_budget_spending 1                                             ;; slider 0-100%
  set G_pct_education_split 0.5                                           ;; slider 0-100%
  set G_infrastructure_impact 1                                         ;; slider 0-100%
  ;------------------- Recycling company related --------------
  set G_tech_capacity_avg 5000                                             ;; slider
  set G_tech_sep_eff_avg 1                                              ;; slider 0-100%

  ; Create the households and municipalities
  create-MPs 1

  create-HHs 10000 [
    set HH_owner one-of MPs                                               ;; households get assigned to a municipality randomly
    set HH_occupancy random 4                                             ;; sets occupancy type randomly
    set HH_perception G_initial_perception_avg                            ;;* (1 + (random 50 - 25) / 100)
    set HH_knowledge G_initial_knowledge_avg                              ;;* (1 + (random 50 - 25) / 100)
  ]

  ask MPs [
    set MP_list_of_HHs HHs with [HH_owner = myself]                       ;; municipalities gather their households
    set MP_budget G_budget_per_person * MP-Population                     ;; budget based on number of households
    set MP_infrastructure random 2                                        ;; infrastruction (centralized/de-centralized) assigned randomly
    set MP_months_overbudget 0
  ]

  ; Create the recycling companies
  create-RCs 3 [
    let capacity round G_tech_capacity_avg
    let sep_eff G_tech_sep_eff_avg
    let tech (list capacity sep_eff 0 0)
    set RC_list_of_techs (list tech)
  ]

  ask MPs [
    output-print (word "Municipality: " self)
    MP-Collect-Waste
    output-print "\n---------Before Transfer---------\n"
    MP-Select-Bid
    output-print (word "Municipality waste\n(total/plastic/recyclable/budget)\n" MP_total_waste "  " MP_plastic_waste "  " MP_recyclable_waste "  " MP_budget "\n")
    output-print (word "Recycling Company/Account Balance")
    ask RCs [output-print (word self "  " RC_account_balance)]
    MP-Transfer
    output-print "\n---------After Transfer---------\n"
    output-print (word "Municipality waste\n(total/plastic/recyclable/budget)\n" MP_total_waste "  " MP_plastic_waste "  " MP_recyclable_waste "  " MP_budget "\n")
    output-print (word "Recycling Company/Account Balance")
    ask RCs [output-print (word self "  " RC_account_balance)]
    output-print "-------------------------"
    let capacity_sum 0
    ask MP_my_contracts [ set capacity_sum capacity_sum + CT_capacity]
    output-print (word "Total capacity of contracts: " capacity_sum)
  ]
end
=======
breed [o o]

>>>>>>> d0ad631e9b469d2d0ed0586dc2271e51463a62f2
@#$#@#$#@
GRAPHICS-WINDOW
1195
424
1236
466
-1
-1
1.0
1
10
1
1
1
0
1
1
1
-16
16
-16
16
0
0
1
ticks
30.0

BUTTON
46
63
110
96
Setup
setup
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

BUTTON
47
109
110
142
Go
go
T
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

TEXTBOX
146
15
430
113
Validation Functions:\nThe following validations test all the functions except for 'setup' or 'go'. The validations ignore the variables defined by sliders. The inputs and outputs of the functions are provided so that the results can be compared to hand calculations. Further information can be found in the Info tab.
11
0.0
1

BUTTON
146
159
431
192
Validate Waste Generation and Collection Routines
setup-waste-validation
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

OUTPUT
460
32
818
472
11

TEXTBOX
463
15
613
33
Validation Results
11
0.0
1

BUTTON
146
120
431
153
Validate Contract Bidding Routines
setup-bid-validation
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

BUTTON
146
199
432
232
Validate Transferring and Accounting Routines
setup-transfer-validation
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

@#$#@#$#@
## WHAT IS IT?

(a general understanding of what the model is trying to show or explain)

## HOW IT WORKS

**Waste Generation and Collection:**
The waste is broken down into three types:

_Total Waste_ - This represents the base waste generated by a household and is inclusive of all types of waste (plastic, paper, organic, etc.). Households generate waste based on their occupancy type and the waste generation equation (waste generated per person per month = 40 - 0.04*x – exp(-0.01*x)*sin(0.3*x) where x is the month). Depending on the occupancy type, the following multipliers are applied: [senior 0.80; single 1; couple 2; family 4]. This ensures that the base waste generation follows the trend senior<single<couple<family.

_Plastic Waste_ - This functionally represents however much of the total waste households separate for plastic recycling. This is impacted by both the perception of importance and the collection infrastructure. This waste is comprised of both recyclable and non-recyclable plastic. How much of the non-recyclable plastic is included here depends on the household's knowledge. Hypotheticall, if the knowledge were perfect, the plastic waste would only be comprised of recyclable waste.

_Recyclable Waste_ - As described in the previous paragraph, this is the amount of the waste that is recyclable .

## HOW TO USE IT

(how to use the model, including a description of each of the items in the Interface tab)

## THINGS TO NOTICE

(suggested things for the user to notice while running the model)

## THINGS TO TRY

(suggested things for the user to try to do (move sliders, switches, etc.) with the model)

## EXTENDING THE MODEL

(suggested things to add or change in the Code tab to make the model more complicated, detailed, accurate, etc.)

## NETLOGO FEATURES

(interesting or unusual features of NetLogo that the model uses, particularly in the Code tab; or where workarounds were needed for missing features)

## RELATED MODELS

(models in the NetLogo Models Library and elsewhere which are of related interest)

## CREDITS AND REFERENCES

(a reference to the model's URL on the web if it has one, as well as any other necessary credits, citations, and links)
@#$#@#$#@
default
true
0
Polygon -7500403 true true 150 5 40 250 150 205 260 250

airplane
true
0
Polygon -7500403 true true 150 0 135 15 120 60 120 105 15 165 15 195 120 180 135 240 105 270 120 285 150 270 180 285 210 270 165 240 180 180 285 195 285 165 180 105 180 60 165 15

arrow
true
0
Polygon -7500403 true true 150 0 0 150 105 150 105 293 195 293 195 150 300 150

box
false
0
Polygon -7500403 true true 150 285 285 225 285 75 150 135
Polygon -7500403 true true 150 135 15 75 150 15 285 75
Polygon -7500403 true true 15 75 15 225 150 285 150 135
Line -16777216 false 150 285 150 135
Line -16777216 false 150 135 15 75
Line -16777216 false 150 135 285 75

bug
true
0
Circle -7500403 true true 96 182 108
Circle -7500403 true true 110 127 80
Circle -7500403 true true 110 75 80
Line -7500403 true 150 100 80 30
Line -7500403 true 150 100 220 30

butterfly
true
0
Polygon -7500403 true true 150 165 209 199 225 225 225 255 195 270 165 255 150 240
Polygon -7500403 true true 150 165 89 198 75 225 75 255 105 270 135 255 150 240
Polygon -7500403 true true 139 148 100 105 55 90 25 90 10 105 10 135 25 180 40 195 85 194 139 163
Polygon -7500403 true true 162 150 200 105 245 90 275 90 290 105 290 135 275 180 260 195 215 195 162 165
Polygon -16777216 true false 150 255 135 225 120 150 135 120 150 105 165 120 180 150 165 225
Circle -16777216 true false 135 90 30
Line -16777216 false 150 105 195 60
Line -16777216 false 150 105 105 60

car
false
0
Polygon -7500403 true true 300 180 279 164 261 144 240 135 226 132 213 106 203 84 185 63 159 50 135 50 75 60 0 150 0 165 0 225 300 225 300 180
Circle -16777216 true false 180 180 90
Circle -16777216 true false 30 180 90
Polygon -16777216 true false 162 80 132 78 134 135 209 135 194 105 189 96 180 89
Circle -7500403 true true 47 195 58
Circle -7500403 true true 195 195 58

circle
false
0
Circle -7500403 true true 0 0 300

circle 2
false
0
Circle -7500403 true true 0 0 300
Circle -16777216 true false 30 30 240

cow
false
0
Polygon -7500403 true true 200 193 197 249 179 249 177 196 166 187 140 189 93 191 78 179 72 211 49 209 48 181 37 149 25 120 25 89 45 72 103 84 179 75 198 76 252 64 272 81 293 103 285 121 255 121 242 118 224 167
Polygon -7500403 true true 73 210 86 251 62 249 48 208
Polygon -7500403 true true 25 114 16 195 9 204 23 213 25 200 39 123

cylinder
false
0
Circle -7500403 true true 0 0 300

dot
false
0
Circle -7500403 true true 90 90 120

face happy
false
0
Circle -7500403 true true 8 8 285
Circle -16777216 true false 60 75 60
Circle -16777216 true false 180 75 60
Polygon -16777216 true false 150 255 90 239 62 213 47 191 67 179 90 203 109 218 150 225 192 218 210 203 227 181 251 194 236 217 212 240

face neutral
false
0
Circle -7500403 true true 8 7 285
Circle -16777216 true false 60 75 60
Circle -16777216 true false 180 75 60
Rectangle -16777216 true false 60 195 240 225

face sad
false
0
Circle -7500403 true true 8 8 285
Circle -16777216 true false 60 75 60
Circle -16777216 true false 180 75 60
Polygon -16777216 true false 150 168 90 184 62 210 47 232 67 244 90 220 109 205 150 198 192 205 210 220 227 242 251 229 236 206 212 183

fish
false
0
Polygon -1 true false 44 131 21 87 15 86 0 120 15 150 0 180 13 214 20 212 45 166
Polygon -1 true false 135 195 119 235 95 218 76 210 46 204 60 165
Polygon -1 true false 75 45 83 77 71 103 86 114 166 78 135 60
Polygon -7500403 true true 30 136 151 77 226 81 280 119 292 146 292 160 287 170 270 195 195 210 151 212 30 166
Circle -16777216 true false 215 106 30

flag
false
0
Rectangle -7500403 true true 60 15 75 300
Polygon -7500403 true true 90 150 270 90 90 30
Line -7500403 true 75 135 90 135
Line -7500403 true 75 45 90 45

flower
false
0
Polygon -10899396 true false 135 120 165 165 180 210 180 240 150 300 165 300 195 240 195 195 165 135
Circle -7500403 true true 85 132 38
Circle -7500403 true true 130 147 38
Circle -7500403 true true 192 85 38
Circle -7500403 true true 85 40 38
Circle -7500403 true true 177 40 38
Circle -7500403 true true 177 132 38
Circle -7500403 true true 70 85 38
Circle -7500403 true true 130 25 38
Circle -7500403 true true 96 51 108
Circle -16777216 true false 113 68 74
Polygon -10899396 true false 189 233 219 188 249 173 279 188 234 218
Polygon -10899396 true false 180 255 150 210 105 210 75 240 135 240

house
false
0
Rectangle -7500403 true true 45 120 255 285
Rectangle -16777216 true false 120 210 180 285
Polygon -7500403 true true 15 120 150 15 285 120
Line -16777216 false 30 120 270 120

leaf
false
0
Polygon -7500403 true true 150 210 135 195 120 210 60 210 30 195 60 180 60 165 15 135 30 120 15 105 40 104 45 90 60 90 90 105 105 120 120 120 105 60 120 60 135 30 150 15 165 30 180 60 195 60 180 120 195 120 210 105 240 90 255 90 263 104 285 105 270 120 285 135 240 165 240 180 270 195 240 210 180 210 165 195
Polygon -7500403 true true 135 195 135 240 120 255 105 255 105 285 135 285 165 240 165 195

line
true
0
Line -7500403 true 150 0 150 300

line half
true
0
Line -7500403 true 150 0 150 150

pentagon
false
0
Polygon -7500403 true true 150 15 15 120 60 285 240 285 285 120

person
false
0
Circle -7500403 true true 110 5 80
Polygon -7500403 true true 105 90 120 195 90 285 105 300 135 300 150 225 165 300 195 300 210 285 180 195 195 90
Rectangle -7500403 true true 127 79 172 94
Polygon -7500403 true true 195 90 240 150 225 180 165 105
Polygon -7500403 true true 105 90 60 150 75 180 135 105

plant
false
0
Rectangle -7500403 true true 135 90 165 300
Polygon -7500403 true true 135 255 90 210 45 195 75 255 135 285
Polygon -7500403 true true 165 255 210 210 255 195 225 255 165 285
Polygon -7500403 true true 135 180 90 135 45 120 75 180 135 210
Polygon -7500403 true true 165 180 165 210 225 180 255 120 210 135
Polygon -7500403 true true 135 105 90 60 45 45 75 105 135 135
Polygon -7500403 true true 165 105 165 135 225 105 255 45 210 60
Polygon -7500403 true true 135 90 120 45 150 15 180 45 165 90

sheep
false
15
Circle -1 true true 203 65 88
Circle -1 true true 70 65 162
Circle -1 true true 150 105 120
Polygon -7500403 true false 218 120 240 165 255 165 278 120
Circle -7500403 true false 214 72 67
Rectangle -1 true true 164 223 179 298
Polygon -1 true true 45 285 30 285 30 240 15 195 45 210
Circle -1 true true 3 83 150
Rectangle -1 true true 65 221 80 296
Polygon -1 true true 195 285 210 285 210 240 240 210 195 210
Polygon -7500403 true false 276 85 285 105 302 99 294 83
Polygon -7500403 true false 219 85 210 105 193 99 201 83

square
false
0
Rectangle -7500403 true true 30 30 270 270

square 2
false
0
Rectangle -7500403 true true 30 30 270 270
Rectangle -16777216 true false 60 60 240 240

star
false
0
Polygon -7500403 true true 151 1 185 108 298 108 207 175 242 282 151 216 59 282 94 175 3 108 116 108

target
false
0
Circle -7500403 true true 0 0 300
Circle -16777216 true false 30 30 240
Circle -7500403 true true 60 60 180
Circle -16777216 true false 90 90 120
Circle -7500403 true true 120 120 60

tree
false
0
Circle -7500403 true true 118 3 94
Rectangle -6459832 true false 120 195 180 300
Circle -7500403 true true 65 21 108
Circle -7500403 true true 116 41 127
Circle -7500403 true true 45 90 120
Circle -7500403 true true 104 74 152

triangle
false
0
Polygon -7500403 true true 150 30 15 255 285 255

triangle 2
false
0
Polygon -7500403 true true 150 30 15 255 285 255
Polygon -16777216 true false 151 99 225 223 75 224

truck
false
0
Rectangle -7500403 true true 4 45 195 187
Polygon -7500403 true true 296 193 296 150 259 134 244 104 208 104 207 194
Rectangle -1 true false 195 60 195 105
Polygon -16777216 true false 238 112 252 141 219 141 218 112
Circle -16777216 true false 234 174 42
Rectangle -7500403 true true 181 185 214 194
Circle -16777216 true false 144 174 42
Circle -16777216 true false 24 174 42
Circle -7500403 false true 24 174 42
Circle -7500403 false true 144 174 42
Circle -7500403 false true 234 174 42

turtle
true
0
Polygon -10899396 true false 215 204 240 233 246 254 228 266 215 252 193 210
Polygon -10899396 true false 195 90 225 75 245 75 260 89 269 108 261 124 240 105 225 105 210 105
Polygon -10899396 true false 105 90 75 75 55 75 40 89 31 108 39 124 60 105 75 105 90 105
Polygon -10899396 true false 132 85 134 64 107 51 108 17 150 2 192 18 192 52 169 65 172 87
Polygon -10899396 true false 85 204 60 233 54 254 72 266 85 252 107 210
Polygon -7500403 true true 119 75 179 75 209 101 224 135 220 225 175 261 128 261 81 224 74 135 88 99

wheel
false
0
Circle -7500403 true true 3 3 294
Circle -16777216 true false 30 30 240
Line -7500403 true 150 285 150 15
Line -7500403 true 15 150 285 150
Circle -7500403 true true 120 120 60
Line -7500403 true 216 40 79 269
Line -7500403 true 40 84 269 221
Line -7500403 true 40 216 269 79
Line -7500403 true 84 40 221 269

wolf
false
0
Polygon -16777216 true false 253 133 245 131 245 133
Polygon -7500403 true true 2 194 13 197 30 191 38 193 38 205 20 226 20 257 27 265 38 266 40 260 31 253 31 230 60 206 68 198 75 209 66 228 65 243 82 261 84 268 100 267 103 261 77 239 79 231 100 207 98 196 119 201 143 202 160 195 166 210 172 213 173 238 167 251 160 248 154 265 169 264 178 247 186 240 198 260 200 271 217 271 219 262 207 258 195 230 192 198 210 184 227 164 242 144 259 145 284 151 277 141 293 140 299 134 297 127 273 119 270 105
Polygon -7500403 true true -1 195 14 180 36 166 40 153 53 140 82 131 134 133 159 126 188 115 227 108 236 102 238 98 268 86 269 92 281 87 269 103 269 113

x
false
0
Polygon -7500403 true true 270 75 225 30 30 225 75 270
Polygon -7500403 true true 30 75 75 30 270 225 225 270
@#$#@#$#@
NetLogo 6.0
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
default
0.0
-0.2 0 0.0 1.0
0.0 1 1.0 0.0
0.2 0 0.0 1.0
link direction
true
0
Line -7500403 true 150 150 90 180
Line -7500403 true 150 150 210 180
@#$#@#$#@
0
@#$#@#$#@
